apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: build-deploy-ui-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  resources:
    - name: my-source-repo
      resourceRef:
        name: hub-ui-repo
    - name: my-image-resource
      resourceRef:
        name: hub-ui-image
  params:
    - name: deployment-name
      value: hub-ui
